- ConfusionMatrix.lua
- test/test_confusion.lua
> Added FAR/FRR computation to ConfusionMatrix.lua.

- adam.lua
http://arxiv.org/pdf/1412.6980v2.pdf
> An implementation of Adam

- adam.lua
- init.lua
Forgot to add it to init.lua and added some comments!
> added adam to init.lua + adam comments

- adam.lua
Error in the paper[1], see discussion here: https://twitter.com/ogrisel/status/568316753593434112
[1] http://arxiv.org/pdf/1412.6980v2.pdf
> lambda default in Adam doesn't make sense

- adam.lua
The sqrt(v) is now being used instead of pow(v, 2).
And I used the default values from the Adam paper:
learningRate=2e-4, epsilon=1e-8, lambda=1-1e-8.
I also optimized the code.
> Fixed optim.adam.

- adam.lua
- test/test_adam.lua
Some cosmetic changes to make the hyper-parameters the same as the latest version of the paper
> Reconcile adam.lua with the latest version of the paper

- init.lua
- rmsprop.lua
- implementation is reasonably efficient
- could be that clone is unnecessary and the square gradients can be calculated in place
- no NAG or momentum (because I've never found it to be helpful)
- eplison values included (because I've always found them to be very useful and the algorithm appears to be sensitive to setting them correctly)
> implementation of rmsprop that uses epsilon values to help stabilise

- Logger.lua
Small change to work under Windows.
> Making things work under windows

- adam.lua
v8 of the paper does not use this parameter.
> remove redundant lambda param from adam

- README.md
> Small typo: Update README.md

- ConfusionMatrix.lua
> Revert "Change ConfusionMatrix accumulator from Float to Long."

- adamax.lua
- init.lua
- test/test_adamax.lua
AdaMax is a variant of Adam. It divides by max(gradient), instead of dividing by the standard deviation.
AdaMax was helpful for me on a task with outliers. The learning rate bounds the maximum change to the parameters.
I added config.epsilon, to avoid dividing by zero, when a parameter was not used yet.
> Add AdaMax.

- doc/index.md
Copied docs from the implemented code for each algorithm, fixed style and improved consistency
> Updated docs for all implemented algorithms

- adagrad.lua
small PR, long-standing internal change.
> add weight decay option to adagrad

- README.md
Just to make things a bit easier to the newcomers :-)
> Includes a pointer to the list of algorithms

- README.md
While I was trying to find out what the `test` dir was about.
> Another addition to the docs

- ConfusionMatrix.lua
If you have millions of predictions looping over them doesn't sound like a good idea.
> Improve ConfusionMatrix performance

- sgd.lua
> Revert "Fix bug with sgd individual learning rates"

- adamax.lua
Hi,
here is a small change to add weight decay to adamax
> add weight decay support to adamax

- adam.lua
- doc/algos.md
Is it possible to add a learning rate decay to Adam ?
I use it everytime.
> Add LearningRateDecay to Adam

- de.lua
- init.lua
- test/test_de.lua
some bugfixes over https://github.com/torch/optim/pull/110
@lzj1769 your name and commit id have been preserved. I improved things and fixed certain bugs.
> Add Differential Evolution

- polyinterp.lua
I also remover all the commented prints in the file (anyway it hasn't been updated for 2 years).
> Fix polyinterp to let lbfgs wtih lswolfe work on GPU
