torch/optim

polyinterp.lua

1. n == 1 will fail line 35 of roots() (check cases roots(Tensor({1, 2})) and roots(Tensor({0, 1, 2, 0})))
2. torch.cat() should add the third argument 1, or it defaults to concat along the 2nd dimension (check case roots(Tensor{1, 4, 2, 0}))

fix 2 bugs in roots() of polyinterp.lua

---

rmsprop.lua
test/test_rmsprop.lua

The current [RMSProp implementation](https://github.com/torch/optim/blob/master/rmsprop.lua) has a critical bug in the following line:
```lua
x:add(-lr, state.tmp)
```
I think the code was trying to **multiply** the learning rate to the `state.tmp` variable and then add it to `x` to perform the parameter update, but right now it's just adding them and adding the result to `x`. I noticed this because my RNN wasn't training with RMSProp at all, when this worked very nicely in my near equivalent Python codebase. 
This pull request fixes the RMSProp implementation and cleans up the code/hyperparams. RMSProp normally has three parameters:
- The learning rate
- The decay rate (`alpha`)
- The smoothing term (`epsilon`)
I fixed the code to contain exactly these three parameters. I also adjusted …

fixing rmsprop bug

---

cg.lua

If the parameters 'x' are a CUDA tensor, then cg fails as is. cg now checks if 'x' is a CUDA tensor and creates state variables appropriately.

Added CUDA support for cg.lua

---

Logger.lua

I propose adding three simple features:
- option to disable showing of plots while still saving plots in a file
- option to set the default symbol
- option to be able to pass a raw command to gnuplot
The new options are 'hidden', meaning they are not exposed in __init() and don't change the old behavior.

New features in Logger

---

ConfusionMatrix.lua

This might be the worlds smallest PR :-)
self.mat is only ever used as an integer accumulator, and so we're wasting a lot of bits...  The max number of samples per matrix element is 2^24 = 16777216, which is actually pretty small (I hit the limit in my particular application).  In retrospect, self.mat should have always been a LongTensor.
I don't think there are any unintended consequences.  But if someone could do a quick scan of the code to double check, that would  be awesome.
Cheers,
Jonathan

Change ConfusionMatrix accumulator from Float to Long.

---

init.lua

It seems like optim is the only library that I use where:
``optim = require('optim')``
doesn't work (at the moment the return value is just ``true``).  To fix this I've added a ``return optim`` statement to the end of ``init.lua``.

return optim in init.lua.

---

lbfgs.lua

List of improvements:
* a pool of buffers is preallocated for `y` and `s` and the histories, to prevent allocation/deallocation inside the loop. An earlier quick check with nvprof when using the old code with CUDA showed a lot of time spent on `cudaFree()` calls--this was the motivation for these fixes. [1]
* "matrix multiplication" / accumulation step is done with a single temporary vector, to avoid linearly growing mem usage in `nCorrection`
* reuse temporary buffers as much as possible
Let me know if you want me to break it into a few commits, see here for an example comparing it to the original implementation, see the regression test `test.lua` here: <https://gist.github.com/bshillingford/315540c787c46e46f13d>. Output is exact for DoubleTensors. I didn't include the regression because …

Memory usage improvements for L-BFGS

---

rprop.lua

Trying to use Rprop on a GPU crash since the parameters will be CudaTensors but the internal variables are ByteTensor. 
This change simply check if the parameters are CudaTensors and in that case convert also the internal variables to CudaTensors (by pushing them to the GPU)

Add GPU support to Rprop

---

nag.lua

This version sets default momentum to 0.9 and adds a check to prevent non-positive momentum.

nag: momentum default is 0.9, added check for non-positive momentum

---

ConfusionMatrix.lua

This has been bugging me for a while.  If you print a confusion matrix with 8 or greater digits, then there's no space separator between the numbers.

fixed printing for counts > 8 digits.

---

sgd.lua

documentation update for config.learningRates, state.evalCounter

---

checkgrad.lua

When the _,dC = opfunc(x) is a gpu tensor, there will be an error:
/bin/luajit: bad argument #2 to '?' (number expected, got userdata)
stack traceback:
[C]: at 0x7fc541dc8040
[C]: in function '__sub'
This is fixed by ``local dC_est = torch.Tensor():typeAs(dC):resizeAs(dC)'' which ensures dC_est and dC have the same tensor type.

checkgrad.lua: tensor type bug when using gpu

---

ConfusionMatrix.lua

Reported in comments to https://github.com/torch/optim/commit/207bb273b7eb0362a77d67a4e2493bfaa0e425db.
`preds` and `targs` can be either a `LongTensor` or a `FloatTensor`, and if their types don't match it crashes when trying to add them.

Fix possible type mismatch in ConfusionMatrix

---

Logger.lua

Following the "logscale commit" on torch/gnuplot, here is the adaptation to use it with torch/optim (useful to display the loss)

add logscale support

---

sgd.lua

The annealed learning rate value was calculated from the single learning rate, even if individual learning rates were supplied. This commit fixes this bug.

Fix bug with sgd individual learning rates

---

rmsprop.lua

With alpha near 1 (e.g. the default value 0.99) the gradient was
likely scaled up due to a division by a number <1 during the first
few iterations.
With the original impl the learning rate had to be set to a much
smaller value when using rmsprop compared to plain-vanilla sgd in
order not to diverge.

Init rmsprop mean square state 'm' with 1 instead 0

---

Logger.lua

A `Logger` can be created and setup in one line
```lua
log = optim.logger('foo'):setNames{'a', 'b'}:style{'-', '-'}
```

One-line Logger initialisation

---

checkgrad.lua

x[i]+eps-2*eps may not result in exactly the same x[i], which may increase approximation error in the gradient estimate.

Reduce numerical errors.

---

checkgrad.lua

When opfunc() simply returns the output state variable of a nn model (ie. when opfunc() simply returns my_net:forward()'s output), the second opfunc() call within the for loop updates not only C2, but also C1. In this case, dC_est is wrongly 0. Avoid this behaviour by blindly copying C1 contents when it is a Tensor/CudaTensor. The overhead should be bearable as C1 is a scalar.

Copy C1 value, in case it is a Tensor reference

---

rmsprop.lua

Reverted to zero mean squared values initialisation `state.m`.
Since the gradients get divided by this moving average it might be sensible to be initialised with ones, since it avoids making big steps in the beginning.
However, this update resulted a substantial decrease in the performance of many of my projects, and I'm sure it's breaking more.

Reverted to zero mean squared values init

---

Logger.lua
doc/logger.md

The `Logger:display(state)` function gives user the flexibility to save the generated plots without displaying them.
Things added or changed as a result of the commits:
+ Added `display` function
+ `setlogscale` function parameter makes more sense now
+ Added documentation for these two functions

Prevent displaying of plots and documentation for it

---

CMakeLists.txt

The `optim` package documentation is now readable from command line with `browse('optim')`, and all routines offered by the API are now viewable with `? optim.routine`.

Enable local doc for inline help
